[package]
name = "ping-pong"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.54", features = ["derive"] }
iroh = "0.95.1"
iroh-ping = "0.7.0"
iroh-tickets = "0.2.0"
pollster = "0.4.0"
rand = "0.9.2"
tokio = "1.49.0"
